import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_MARKER = '<!-- GENERATED BY orig_test_v2/src/build.mjs -->';

function optimizeMarkup(markup, optimizedAssets) {
  if (!markup || !optimizedAssets || !Object.keys(optimizedAssets).length) return markup;
  return Object.entries(optimizedAssets).reduce((result, [source, target]) => (
    [
      [`../assets/${source}`, `../assets/${target}`],
      [`assets/${source}`, `assets/${target}`],
    ].reduce((next, [from, to]) => next.split(from).join(to), result)
  ), markup);
}

export async function renderDocument({
  rootDir,
  document,
  manifest,
  canonicalBlocks = {},
  optimizedAssets = {},
}) {
  const read = (relativePath) => readFile(path.join(rootDir, relativePath), 'utf8');
  const optimize = (markup) => optimizeMarkup(markup, optimizedAssets);
  // Keep the source document byte-stable when the build marker is stripped.
  // Appending the marker inside <head> avoids introducing a leading blank line.
  const head = `${optimize(document.headInner)}${GENERATED_MARKER}`;
  const fragments = [];
  const sharedParts = manifest.shared ?? {};
  const pageCanonicalBlocks = canonicalBlocks[manifest.id] ?? {};
  const manifestBlocks = manifest.blocks ?? {};

  for (const part of manifest.order) {
    const partMeta = document.parts.find((item) => item.key === part);
    if (!partMeta) throw new Error(`Missing part "${part}" for ${manifest.id}`);
    const source = manifestBlocks[part]
      ?? sharedParts[part]
      ?? pageCanonicalBlocks[part]
      ?? partMeta.file;
    fragments.push(optimize(await read(source)));
  }

  const bodyBeforeMain = optimize(document.bodyBeforeMain);
  const mainInnerTrailing = optimize(document.mainInnerTrailing);
  const bodyAfterMain = manifest.kind === 'inner' && document.bodyAfterMain.includes('../shared/production-site-shell.js')
    ? optimize(document.bodyAfterMain)
      .replace(
      '<script src="../shared/production-site-shell.js',
      '<script src="../shared/inner-shell-markup.js?v=20260831-cache-v4"></script>\n    <script src="../shared/production-site-shell.js'
      )
    : optimize(document.bodyAfterMain);

  return [
    document.doctype,
    document.htmlOpen,
    '\n',
    document.headOpen,
    head,
    document.headClose,
    '\n',
    document.bodyOpen,
    bodyBeforeMain,
    document.mainOpen,
    fragments.join(''),
    mainInnerTrailing,
    document.mainClose,
    bodyAfterMain,
    document.bodyClose,
    '\n',
    document.htmlClose,
    '\n\r\n\r\n',
  ].join('');
}
