import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_MARKER = '<!-- GENERATED BY orig_test_v2/src/build.mjs -->';

function optimizeMarkup(markup, optimizedAssets) {
  if (!markup || !optimizedAssets || !Object.keys(optimizedAssets).length) return markup;
  return Object.entries(optimizedAssets).reduce((result, [source, target]) => (
    [
      [`../assets/${source}`, `../assets/${target}`],
      [`assets/${source}`, `assets/${target}`],
    ].reduce((next, [from, to]) => next.split(from).join(to), result)
  ), markup);
}

export async function renderDocument({
  rootDir,
  document,
  manifest,
  canonicalBlocks = {},
  optimizedAssets = {},
  templateContext = {},
  shell = {},
}) {
  const read = (relativePath) => readFile(path.join(rootDir, relativePath), 'utf8');
  const optimize = (markup) => optimizeMarkup(markup, optimizedAssets);
  const compile = (markup, source = manifest.id) => markup.replace(/\{\{([A-Z_]+)\}\}/g, (token, key) => {
    if (!(key in templateContext)) throw new Error(`Unknown token ${token} in ${source}`);
    return templateContext[key];
  });
  const fragments = [];
  const sharedParts = manifest.shared ?? {};
  const pageCanonicalBlocks = canonicalBlocks[manifest.id] ?? {};
  const manifestBlocks = manifest.blocks ?? {};

  for (const part of manifest.order) {
    const partMeta = document.parts.find((item) => item.key === part);
    if (!partMeta) throw new Error(`Missing part "${part}" for ${manifest.id}`);
    const source = manifestBlocks[part]
      ?? sharedParts[part]
      ?? pageCanonicalBlocks[part]
      ?? partMeta.file;
    fragments.push(optimize(compile(await read(source), source)));
  }

  let bodyBeforeMain = optimize(compile(document.bodyBeforeMain));
  let mainInner = fragments.join('');
  if (manifest.kind !== 'home') {
    bodyBeforeMain = bodyBeforeMain.replace(/<div\s+data-site-header\s*><\/div>/, optimize(shell.header || ''));
    const contactSlot = /<div\s+data-cta(?:\s+data-title="[^"]*")?\s*><\/div>/g;
    const footerSlot = /<div\s+data-site-footer\s*><\/div>/g;
    const hasContactSlot = contactSlot.test(mainInner);
    contactSlot.lastIndex = 0;
    mainInner = mainInner.replace(contactSlot, optimize(shell.contact || ''));
    if (!hasContactSlot && footerSlot.test(mainInner)) {
      footerSlot.lastIndex = 0;
      mainInner = mainInner.replace(footerSlot, `${optimize(shell.contact || '')}${optimize(shell.footer || '')}`);
    } else {
      footerSlot.lastIndex = 0;
      mainInner = mainInner.replace(footerSlot, optimize(shell.footer || ''));
    }
  }
  const mainInnerTrailing = optimize(document.mainInnerTrailing);
  const stylesheetPattern = /<link\b(?=[^>]*\brel=(["'])stylesheet\1)[^>]*>/gi;
  const bodyAfterMainSource = optimize(document.bodyAfterMain);
  const deferredStyles = bodyAfterMainSource.match(stylesheetPattern) ?? [];
  const bodyAfterMain = bodyAfterMainSource.replace(stylesheetPattern, '').replace(/^[ \t]+$/gm, '');
  const innerMotionPages = new Set(['news-articles', 'service-detail']);
  const innerMotionRuntime = !innerMotionPages.has(manifest.id)
    ? ''
    : '\n  <script src="../shared/vendor/motion-13.2.0.min.js?v=20260911-cache-v10"></script>';
  // Keep render-blocking styles in <head>. Some legacy manifests still store
  // these links beside the closing scripts, which otherwise causes a visible
  // first-paint layout shift before the final inner-page geometry arrives.
  const head = `${optimize(document.headInner)}${deferredStyles.length ? `${deferredStyles.join('\n')}\n` : ''}${GENERATED_MARKER}`;

  return [
    document.doctype,
    document.htmlOpen,
    '\n',
    document.headOpen,
    head,
    document.headClose,
    '\n',
    document.bodyOpen,
    bodyBeforeMain,
    document.mainOpen,
    mainInner,
    mainInnerTrailing,
    document.mainClose,
    innerMotionRuntime,
    bodyAfterMain,
    document.bodyClose,
    '\n',
    document.htmlClose,
    '\n\r\n\r\n',
  ].join('');
}
