import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const GENERATED_MARKER = '<!-- GENERATED BY orig_test_v2/src/build.mjs -->';

function injectPageSeo(head, seo) {
  if (!seo) return head;
  let result = head.replace(/<title>.*?<\/title>/, `<title>${seo.title}</title>`);
  const tags = [
    `<meta name="description" content="${seo.description}">`,
    `<meta name="robots" content="${seo.robots ?? 'index,follow'}">`,
    '<meta property="og:type" content="website">',
    `<meta property="og:title" content="${seo.title}">`,
    `<meta property="og:description" content="${seo.ogDescription ?? seo.description}">`,
    `<meta property="og:url" content="${seo.canonical}">`,
    `<link rel="canonical" href="${seo.canonical}">`,
  ].join('\n');
  return result.replace(/(<link\b)/, `${tags}\n$1`);
}

function optimizeMarkup(markup, optimizedAssets) {
  if (!markup || !optimizedAssets || !Object.keys(optimizedAssets).length) return markup;
  return Object.entries(optimizedAssets).reduce((result, [source, target]) => (
    [
      [`../assets/${source}`, `../assets/${target}`],
      [`assets/${source}`, `assets/${target}`],
    ].reduce((next, [from, to]) => next.split(from).join(to), result)
  ), markup);
}
export async function renderDocument({
  rootDir,
  document,
  manifest,
  canonicalBlocks = {},
  optimizedAssets = {},
  templateContext = {},
  shell = {},
}) {
  const read = (relativePath) => readFile(path.join(rootDir, relativePath), 'utf8');
  const optimize = (markup) => optimizeMarkup(markup, optimizedAssets);
  const compile = (markup, source = manifest.id) => markup.replace(/\{\{([A-Z_]+)\}\}/g, (token, key) => {
    if (!(key in templateContext)) throw new Error(`Unknown token ${token} in ${source}`);
    return templateContext[key];
  });
  const fragments = [];
  const sharedParts = manifest.shared ?? {};
  const pageCanonicalBlocks = canonicalBlocks[manifest.id] ?? {};
  const manifestBlocks = manifest.blocks ?? {};

  for (const part of manifest.order) {
    const partMeta = document.parts.find((item) => item.key === part);
    if (!partMeta) throw new Error(`Missing part "${part}" for ${manifest.id}`);
    const source = manifestBlocks[part]
      ?? sharedParts[part]
      ?? pageCanonicalBlocks[part]
      ?? partMeta.file;
    fragments.push(optimize(compile(await read(source), source)));
  }

  let bodyBeforeMain = optimize(compile(document.bodyBeforeMain));
  let mainInner = fragments.join('');
  const restoredInnerPages = new Set(['services', 'projects-clients', 'completed-works', 'contacts']);
  if (manifest.kind !== 'home') {
    bodyBeforeMain = bodyBeforeMain.replace(/<div\s+data-site-header\s*><\/div>/, optimize(shell.header || ''));
    const contactSlot = /<div\s+data-cta(?:\s+data-title="[^"]*")?\s*><\/div>/g;
    const footerSlot = /<div\s+data-site-footer\s*><\/div>/g;
    const hasContactSlot = contactSlot.test(mainInner);
    contactSlot.lastIndex = 0;
    mainInner = mainInner.replace(contactSlot, optimize(shell.contact || ''));
    if (!hasContactSlot && footerSlot.test(mainInner)) {
      footerSlot.lastIndex = 0;
      mainInner = mainInner.replace(footerSlot, `${optimize(shell.contact || '')}${optimize(shell.footer || '')}`);
    } else {
      footerSlot.lastIndex = 0;
      mainInner = mainInner.replace(footerSlot, optimize(shell.footer || ''));
    }
    if (!restoredInnerPages.has(manifest.id)) mainInner = mainInner.replace(/> Email</g, '> Почта<');
  }
  const mainInnerTrailing = optimize(document.mainInnerTrailing);
  const stylesheetPattern = /<link\b(?=[^>]*\brel=(["'])stylesheet\1)[^>]*>/gi;
  const isRedesignedInner = manifest.kind !== 'home' && !restoredInnerPages.has(manifest.id) && !manifest.skipInnerRedesign;
  const shellCacheVersion = manifest.id.startsWith('service-')
    ? '20260914-template-compact-v5'
    : '20260912-inner-hero-rhythm-v5';
  let bodyAfterMainSource = optimize(document.bodyAfterMain)
    .replace(/production-site-shell\.js\?v=[^\"]+/g, `production-site-shell.js?v=${shellCacheVersion}`);
  if (manifest.id === 'services') {
    bodyAfterMainSource = bodyAfterMainSource.replace(
      /production-services-page\.css\?v=[^\"]+/g,
      'production-services-page.css?v=20260914-services-container-align-v2'
    );
  }
  if (manifest.id === 'projects-clients' || manifest.id === 'completed-works') {
    bodyAfterMainSource = bodyAfterMainSource.replace(
      /production-projects-clients-reference\.css\?v=[^\"]+/g,
      'production-projects-clients-reference.css?v=20260914-projects-container-align-v1'
    );
  }
  if (isRedesignedInner) bodyAfterMainSource = bodyAfterMainSource.replace(/> Email</g, '> Почта<');
  const deferredStyles = bodyAfterMainSource.match(stylesheetPattern) ?? [];
  const bodyAfterMain = bodyAfterMainSource.replace(stylesheetPattern, '').replace(/^[ \t]+$/gm, '');
  const innerMotionPages = new Set(['news-articles', 'service-detail']);
  const innerMotionRuntime = !innerMotionPages.has(manifest.id)
    ? ''
    : '\n  <script src="../shared/vendor/motion-13.2.0.min.js?v=20260911-cache-v10"></script>';
  const innerRedesignStyles = isRedesignedInner
    ? '<link rel="stylesheet" href="../shared/production-inner-redesign-v1.css?v=20260912-inner-redesign-v33">'
    : '';
  const homeServicesLayoutGuard = manifest.kind === 'home'
    ? '<style id="homepage-services-07-layout">@media (min-width:1200px){main.site > .services{min-height:435px;height:auto;}}</style>'
    : '';
  // Keep render-blocking styles in <head>. Some legacy manifests still store
  // these links beside the closing scripts, which otherwise causes a visible
  // first-paint layout shift before the final inner-page geometry arrives.
  let headInnerSource = optimize(compile(document.headInner))
    .replaceAll('https://ooopdp.ru/orig_test_v2/', 'https://ooopdp.ru/');
  headInnerSource = injectPageSeo(headInnerSource, manifest.seo);
  if (manifest.id === 'news-articles') {
    headInnerSource = headInnerSource.replace(
      /production-articles-index-reference\.css\?v=[^\"]+/g,
      'production-articles-index-reference.css?v=20260912-hero-white-footer-dark-v2'
    );
  }
  const pageStyles = (manifest.headStyles ?? [])
    .map((href) => `<link rel="stylesheet" href="${href}">`)
    .join('\n');
  const head = [headInnerSource, deferredStyles.length ? deferredStyles.join('\n') + '\n' : '', innerRedesignStyles, pageStyles ? `${pageStyles}\n` : '', homeServicesLayoutGuard, GENERATED_MARKER].join('');

  return [
    document.doctype,
    document.htmlOpen,
    '\n',
    document.headOpen,
    head,
    document.headClose,
    '\n',
    document.bodyOpen,
    bodyBeforeMain,
    document.mainOpen,
    mainInner,
    mainInnerTrailing,
    document.mainClose,
    innerMotionRuntime,
    bodyAfterMain,
    document.bodyClose,
    '\n',
    document.htmlClose,
    '\n\r\n\r\n',
  ].join('');
}

