import { access, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { renderDocument } from './blocks/layout/template.js';
import { siteData } from './data/site-data.js';

const srcDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
const siteDir = path.resolve(srcDir, '..');
const marker = '<!-- GENERATED BY orig_test_v2/src/build.mjs -->';
const tokenPattern = /\{\{([A-Z_]+)\}\}/g;

function relativeHref(output, target) {
  const from = path.posix.dirname(output);
  return path.posix.relative(from === '.' ? '' : from, target) || path.posix.basename(target);
}

function shellContext(manifest) {
  const isHome = manifest.id === 'home';
  const href = (target) => relativeHref(manifest.output, target);
  const active = {
    home: isHome,
    services: ['services', 'service-detail'].includes(manifest.id),
    cases: ['projects-clients', 'project-red-october', 'completed-works'].includes(manifest.id),
    contacts: ['contacts', 'privacy-policy'].includes(manifest.id),
    articles: ['news-articles', 'article-detail', 'documents-materials', 'article-construction-control', 'article-executive-documentation'].includes(manifest.id),
  };
  const state = (name) => active[name] ? 'active' : '';
  const aria = (name) => active[name] ? 'aria-current="page"' : '';
  const asset = (relativePath) => href(`assets/${relativePath}`);
  return Object.freeze({
    HOME: isHome ? '#top' : href(siteData.routes.home),
    SERVICES: href(siteData.routes.services),
    CASES: href(siteData.routes.cases),
    PROJECTS: href(siteData.routes.projects),
    ARTICLES: href(siteData.routes.articles),
    CONTACTS: href(siteData.routes.contacts),
    PRIVACY: href(siteData.routes.privacy),
    LOGO: asset('pdp-official-logo.svg'),
    FOOTER_LOGO: asset('pdp-official-logo-footer.svg'),
    CONTACT_PATTERN: asset('patterns/pdp-logo-parallax.png'),
    PRESENTATION: asset('documents/pdp-presentation.pdf'),
    ACTIVE_HOME: state('home'),
    ACTIVE_SERVICES: state('services'),
    ACTIVE_CASES: state('cases'),
    ACTIVE_CONTACTS: state('contacts'),
    ACTIVE_ARTICLES: state('articles'),
    ARIA_HOME: aria('home'),
    ARIA_SERVICES: aria('services'),
    ARIA_CASES: aria('cases'),
    ARIA_CONTACTS: aria('contacts'),
    ARIA_ARTICLES: aria('articles'),
  });
}

function compileTemplate(markup, context, source) {
  const compiled = markup.replace(tokenPattern, (token, key) => {
    if (!(key in context)) throw new Error(`Unknown token ${token} in ${source}`);
    return context[key];
  });
  if (compiled.match(tokenPattern)) throw new Error(`Unresolved template token in ${source}`);
  return compiled;
}

function assertInsideSite(relativePath) {
  const absolute = path.resolve(siteDir, relativePath);
  if (!absolute.startsWith(`${siteDir}${path.sep}`) && absolute !== siteDir) {
    throw new Error(`Refusing to write outside orig_test_v2: ${relativePath}`);
  }
  if (absolute.includes('PDP-backup-before-structure')) {
    throw new Error(`Refusing to touch backup path: ${absolute}`);
  }
  return absolute;
}

async function manifestFiles() {
  const entries = await readdir(path.join(srcDir, 'pages'), { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.page.js'))
    .map((entry) => entry.name)
    .sort();
}

async function loadManifest(fileName) {
  const url = `${pathToFileURL(path.join(srcDir, 'pages', fileName)).href}?v=${Date.now()}`;
  const module = await import(url);
  return module.default;
}

async function renderManifest(manifest) {
  const documentPath = path.join(srcDir, manifest.sourceDir, 'document.json');
  const document = JSON.parse(await readFile(documentPath, 'utf8'));
  if (document.headInner.includes(marker)) throw new Error(`${manifest.id} source already contains the generated marker.`);
  const context = shellContext(manifest);
  const shellEntries = await Promise.all(Object.entries(siteData.sharedBlocks).map(async ([name, source]) => [
    name,
    compileTemplate(await readFile(path.join(srcDir, source), 'utf8'), context, source),
  ]));
  return renderDocument({
    rootDir: srcDir,
    document,
    manifest,
    canonicalBlocks: siteData.canonicalBlocks,
    optimizedAssets: siteData.innerOptimizedAssets,
    templateContext: context,
    shell: Object.fromEntries(shellEntries),
  });
}

const mode = process.argv.includes('--write') ? 'write' : 'check';
const files = await manifestFiles();
let changed = 0;

for (const fileName of files) {
  const manifest = await loadManifest(fileName);
  const outputPath = assertInsideSite(manifest.output);
  const rendered = await renderManifest(manifest);
  let current = '';
  try {
    current = await readFile(outputPath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (current !== rendered) {
    changed += 1;
    if (mode === 'write') await writeFile(outputPath, rendered, 'utf8');
  }
}

if (mode === 'check') {
  console.log(`Architecture check: ${files.length} manifests, ${changed} outputs differ.`);
  if (changed > 0) process.exitCode = 1;
} else {
  console.log(`Built ${files.length} pages; updated ${changed} generated outputs.`);
}
