import { access, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { renderDocument } from './blocks/layout/template.js';
import { siteData } from './data/site-data.js';

const srcDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
const siteDir = path.resolve(srcDir, '..');
const marker = '<!-- GENERATED BY orig_test_v2/src/build.mjs -->';

function assertInsideSite(relativePath) {
  const absolute = path.resolve(siteDir, relativePath);
  if (!absolute.startsWith(`${siteDir}${path.sep}`) && absolute !== siteDir) {
    throw new Error(`Refusing to write outside orig_test_v2: ${relativePath}`);
  }
  if (absolute.includes('PDP-backup-before-structure')) {
    throw new Error(`Refusing to touch backup path: ${absolute}`);
  }
  return absolute;
}

async function manifestFiles() {
  const entries = await readdir(path.join(srcDir, 'pages'), { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.page.js'))
    .map((entry) => entry.name)
    .sort();
}

async function loadManifest(fileName) {
  const url = `${pathToFileURL(path.join(srcDir, 'pages', fileName)).href}?v=${Date.now()}`;
  const module = await import(url);
  return module.default;
}

async function renderManifest(manifest) {
  const documentPath = path.join(srcDir, manifest.sourceDir, 'document.json');
  const document = JSON.parse(await readFile(documentPath, 'utf8'));
  if (document.headInner.includes(marker)) throw new Error(`${manifest.id} source already contains the generated marker.`);
  return renderDocument({
    rootDir: srcDir,
    document,
    manifest,
    canonicalBlocks: siteData.canonicalBlocks,
    optimizedAssets: siteData.innerOptimizedAssets,
  });
}

async function renderInnerShellData() {
  const templatePaths = {
    header: 'blocks/header/inner-template.html',
    contact: 'blocks/contact-form/inner-template.html',
    footer: 'blocks/footer/inner-template.html',
  };
  const templates = Object.fromEntries(
    await Promise.all(Object.entries(templatePaths).map(async ([key, relativePath]) => [
      key,
      await readFile(path.join(srcDir, relativePath), 'utf8'),
    ])),
  );
  const optimizedTemplates = Object.fromEntries(
    Object.entries(templates).map(([key, markup]) => [
      key,
      Object.entries(siteData.innerOptimizedAssets).reduce((result, [source, target]) => (
        [
          [`../assets/${source}`, `../assets/${target}`],
          [`assets/${source}`, `assets/${target}`],
        ].reduce((next, [from, to]) => next.split(from).join(to), result)
      ), markup),
    ]),
  );
  return `/* GENERATED BY orig_test_v2/src/build.mjs — inner shell templates */\nwindow.PDP_INNER_SHELL_TEMPLATES = Object.freeze(${JSON.stringify(optimizedTemplates)});\n`;
}

const mode = process.argv.includes('--write') ? 'write' : 'check';
const files = await manifestFiles();
let changed = 0;

const shellOutputPath = assertInsideSite('shared/inner-shell-markup.js');
const shellRendered = await renderInnerShellData();
let currentShell = '';
try {
  currentShell = await readFile(shellOutputPath, 'utf8');
} catch (error) {
  if (error.code !== 'ENOENT') throw error;
}
if (currentShell !== shellRendered) {
  changed += 1;
  if (mode === 'write') await writeFile(shellOutputPath, shellRendered, 'utf8');
}

for (const fileName of files) {
  const manifest = await loadManifest(fileName);
  const outputPath = assertInsideSite(manifest.output);
  const rendered = await renderManifest(manifest);
  let current = '';
  try {
    current = await readFile(outputPath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (current !== rendered) {
    changed += 1;
    if (mode === 'write') await writeFile(outputPath, rendered, 'utf8');
  }
}

if (mode === 'check') {
  console.log(`Architecture check: ${files.length} manifests, ${changed} outputs differ.`);
  if (changed > 0) process.exitCode = 1;
} else {
  console.log(`Built ${files.length} pages + inner shell data; updated ${changed} generated outputs.`);
}
